//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_courseAllocation
    {
        public int AllocationID { get; set; }
        public int SubjectId { get; set; }
        public int FacultyId { get; set; }
        public string ClassId { get; set; }
        public string Day { get; set; }
        public double StartHour { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_faculty tbl_faculty { get; set; }
        public virtual tbl_subjects tbl_subjects { get; set; }
    }
}
