//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_class
    {
        public tbl_class()
        {
            this.tbl_courseAllocation = new HashSet<tbl_courseAllocation>();
            this.tbl_students = new HashSet<tbl_students>();
        }
    
        public string ClassId { get; set; }
        public int SemesterNo { get; set; }
    
        public virtual ICollection<tbl_courseAllocation> tbl_courseAllocation { get; set; }
        public virtual ICollection<tbl_students> tbl_students { get; set; }
    }
}
